# Generated by Django 4.2.8 on 2023-12-25 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0003_internship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='internship',
            name='start_date',
            field=models.DateField(),
        ),
    ]
