# Generated by Django 4.2.8 on 2023-12-26 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protfolio', '0004_alter_internship_end_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Internship',
        ),
    ]
